import { Restaurant } from "@/types/restaurant";

export const restaurants: Restaurant[] = [
  {
    id: "rest_1",
    name: "Maple Spice Kitchen",
    slug: "maple-spice-kitchen",
    description:
      "Authentic Indian cuisine with a modern Canadian twist.",
    cuisine: ["Indian", "Biryani", "North Indian"],
    rating: 4.7,
    featured: true,
    priceRange: "$$",
    estimatedDeliveryTime: 30,
    bannerColor: "#FF6B35",
    totalRatings: 3200,
    reviewCount: 1875,
    deliveryTime: "25-35 min",
    minOrder: 15,
    deliveryFee: 2.99,
    serviceFee: 1.99,
    address: {
      street: "123 King Street West",
      city: "Toronto",
      state: "Ontario",
      zipCode: "M5H 1J9",
      coordinates: {
        latitude: 43.6532,
        longitude: -79.3832,
      },
    },
    images: {
      cover:[
        "https://images.unsplash.com/photo-1585937421612-70a008356fbe",
        "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
        "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445"
    ],
      logo:
        "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
      gallery: [],
    },
    operatingHours: {
      monday: { isOpen: true, openTime: "10:00", closeTime: "22:00" },
      tuesday: { isOpen: true, openTime: "10:00", closeTime: "22:00" },
      wednesday: { isOpen: true, openTime: "10:00", closeTime: "22:00" },
      thursday: { isOpen: true, openTime: "10:00", closeTime: "22:00" },
      friday: { isOpen: true, openTime: "10:00", closeTime: "23:00" },
      saturday: { isOpen: true, openTime: "10:00", closeTime: "23:00" },
      sunday: { isOpen: true, openTime: "11:00", closeTime: "21:00" },
    },
    isOpen: true,
    isActive: true,
    popularItems: ["butter-chicken", "chicken-biryani"],
    tags: ["trending", "top rated"],
    averageOrderValue: 35,
  },

  {
    id: "rest_2",
    name: "Pacific Sushi House",
    slug: "pacific-sushi-house",
    description:
      "Fresh sushi and Japanese specialties from Vancouver.",
    cuisine: ["Japanese", "Sushi"],
    rating: 4.8,
     featured: true,
  priceRange: "$$",
  estimatedDeliveryTime: 30,
  bannerColor: "#FF6B35",
    totalRatings: 4100,
    reviewCount: 2200,
    deliveryTime: "20-30 min",
    minOrder: 20,
    deliveryFee: 3.49,
    serviceFee: 1.99,
    address: {
      street: "456 Robson Street",
      city: "Vancouver",
      state: "British Columbia",
      zipCode: "V6B 2B7",
      coordinates: {
        latitude: 49.2827,
        longitude: -123.1207,
      },
    },
    images: {
      cover:
       [ "https://images.unsplash.com/photo-1579871494447-9811cf80d66c"],
      logo:
        "https://images.unsplash.com/photo-1553621042-f6e147245754",
      gallery: [],
    },
    operatingHours: {
      monday: { isOpen: true, openTime: "11:00", closeTime: "22:00" },
      tuesday: { isOpen: true, openTime: "11:00", closeTime: "22:00" },
      wednesday: { isOpen: true, openTime: "11:00", closeTime: "22:00" },
      thursday: { isOpen: true, openTime: "11:00", closeTime: "22:00" },
      friday: { isOpen: true, openTime: "11:00", closeTime: "23:00" },
      saturday: { isOpen: true, openTime: "11:00", closeTime: "23:00" },
      sunday: { isOpen: true, openTime: "11:00", closeTime: "21:00" },
    },
    isOpen: true,
    isActive: true,
    popularItems: ["salmon-roll", "dragon-roll"],
    tags: ["healthy", "popular"],
    averageOrderValue: 42,
  },

  {
    id: "rest_3",
    name: "Montreal Smokehouse",
    slug: "montreal-smokehouse",
    description:
      "Famous Montreal smoked meat sandwiches and BBQ platters.",
    cuisine: ["BBQ", "Canadian"],
    rating: 4.6,
     featured: true,
  priceRange: "$$",
  estimatedDeliveryTime: 30,
  bannerColor: "#FF6B35",
    totalRatings: 2900,
    reviewCount: 1500,
    deliveryTime: "30-40 min",
    minOrder: 18,
    deliveryFee: 2.99,
    serviceFee: 1.99,
    address: {
      street: "789 Rue Sainte-Catherine",
      city: "Montreal",
      state: "Quebec",
      zipCode: "H3B 1E3",
      coordinates: {
        latitude: 45.5017,
        longitude: -73.5673,
      },
    },
    images: {
      cover:
        ["https://images.unsplash.com/photo-1528605248644-14dd04022da1"],
      logo:
        "https://images.unsplash.com/photo-1550547660-d9450f859349",
      gallery: [],
    },
    operatingHours: {
      monday: { isOpen: true, openTime: "11:00", closeTime: "22:00" },
      tuesday: { isOpen: true, openTime: "11:00", closeTime: "22:00" },
      wednesday: { isOpen: true, openTime: "11:00", closeTime: "22:00" },
      thursday: { isOpen: true, openTime: "11:00", closeTime: "22:00" },
      friday: { isOpen: true, openTime: "11:00", closeTime: "23:00" },
      saturday: { isOpen: true, openTime: "11:00", closeTime: "23:00" },
      sunday: { isOpen: true, openTime: "12:00", closeTime: "21:00" },
    },
    isOpen: true,
    isActive: true,
    popularItems: ["smoked-meat-sandwich", "bbq-ribs"],
    tags: ["local favorite"],
    averageOrderValue: 38,
  },

  {
    id: "rest_4",
    name: "Northern Poutine Co.",
    slug: "northern-poutine-co",
    description:
      "Classic Canadian comfort food and gourmet poutines.",
    cuisine: ["Canadian", "Fast Food"],
    rating: 4.5,
     featured: true,
  priceRange: "$$",
  estimatedDeliveryTime: 30,
  bannerColor: "#FF6B35",
    totalRatings: 5100,
    reviewCount: 2700,
    deliveryTime: "15-25 min",
    minOrder: 10,
    deliveryFee: 1.99,
    serviceFee: 1.49,
    address: {
      street: "210 Sparks Street",
      city: "Ottawa",
      state: "Ontario",
      zipCode: "K1P 5C7",
      coordinates: {
        latitude: 45.4215,
        longitude: -75.6972,
      },
    },
    images: {
      cover:
        ["https://images.unsplash.com/photo-1513104890138-7c749659a591"],
      logo:
        "https://images.unsplash.com/photo-1568901346375-23c9450c58cd",
      gallery: [],
    },
    operatingHours: {
      monday: { isOpen: true, openTime: "09:00", closeTime: "22:00" },
      tuesday: { isOpen: true, openTime: "09:00", closeTime: "22:00" },
      wednesday: { isOpen: true, openTime: "09:00", closeTime: "22:00" },
      thursday: { isOpen: true, openTime: "09:00", closeTime: "22:00" },
      friday: { isOpen: true, openTime: "09:00", closeTime: "23:00" },
      saturday: { isOpen: true, openTime: "09:00", closeTime: "23:00" },
      sunday: { isOpen: true, openTime: "10:00", closeTime: "21:00" },
    },
    isOpen: true,
    isActive: true,
    popularItems: ["classic-poutine", "loaded-poutine"],
    tags: ["free delivery", "canadian"],
    averageOrderValue: 24,
  },
];